/**
 * @file connconfig.hpp
 * @brief Holds Connection Configuration setting
 * @author Peter Stahl (xstahl01)
 */

#ifndef CONNCONFIG_HPP
#define CONNCONFIG_HPP

#include <cstdint>
#include <string>

#include "rdt_constants.hpp"

struct ConnConfig
{
    static constexpr uint32_t DEFAULT_TIMEOUT_S = 1;
    /// @brief Default send/receive windows size in segment
    static constexpr uint32_t DEFAULT_WINDOW_SIZE = 30;
    static constexpr uint16_t MIN_PORT = 1;
    static constexpr uint16_t MAX_PORT = 65535;

    rdt::AppMode mode;
    std::string host; // client only 
    uint16_t port = 0;
    
    uint32_t timeout_s = DEFAULT_TIMEOUT_S;
    uint32_t window_size = DEFAULT_WINDOW_SIZE;
    uint32_t conn_id = 0; //generated by AppFactory
    
    std::string input_path; // client: -i empty = stdin
    std::string output_path; //server -o, empty = stdout
    std::string bind_adress; // server -a, empty = all interfaces  
};


#endif //CONNCONFIG_HPP
